BuzzJean/Models/Quiz.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace BuzzJean.Models
{
    [Table("Quizzes")]
    public class Quiz
    {
        public int id { get; set; }
        public string title { get; set; }
        public virtual List<Question> questions { get; set; }
    }

    public class Question
    {
        public int id { get; set; }
        public string question { get; set; }
        public virtual Quiz quiz { get; set; }
        public virtual List<Answer> answers { get; set; }
    }

    public class Answer
    {
        public int id { get; set; }
        public string answer { get; set; }
        public int value { get; set; }
        public virtual Question question { get; set; }
    }

    public class DbConnection:DbContext
    {
        public DbSet<Quiz>     Quizzes   { get; set; }
        public DbSet<Question> Questions { get; set; }
        public DbSet<Answer>   Answers   { get; set; }
    }
}

BuzzJean/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BuzzJean.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BuzzJean/Controllers/MakeController.cs
using BuzzJean.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BuzzJean.Controllers
{
    public class MakeController : Controller
    {
        DbConnection newConnection = new DbConnection();

        // GET: Make
        public ActionResult Index()
        {
            List<Quiz> quizzes = newConnection.Quizzes.ToList();
            return View(quizzes);
        }

        // GET: Make/Quiz/:id
        public ActionResult Quiz(int id)
        {
            //find which quiz
            Quiz currentQuiz = newConnection.Quizzes.Find(id);
            //pass quiz to view
            return View(currentQuiz);
        }

        // GET: Make/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

       // POST: Make/Create
       [HttpPost]
        public ActionResult Create(string title)
        {
            //create a new quiz
            Quiz newQuiz = new Quiz();
            newQuiz.title = title;

            //save the quiz in the db
            newConnection.Quizzes.Add(newQuiz);
            newConnection.SaveChanges();

            //redirect to Index
            return RedirectToAction("Index");
        }

        // GET: Make/NewQuestion/:id
        [HttpGet]
        public ActionResult NewQuestion(int id)
        {
            ViewBag.quiz_id = id;
            return View();
        }

        // POST: Make/CreateQuestion
        [HttpPost]
        public ActionResult CreateQuestion(string question, int quiz_id)
        {
            //create a new question
            Question newQuestion = new Question();
            newQuestion.question = question;
            newQuestion.quiz = newConnection.Quizzes.Find(quiz_id);

            //save the question in the db
            newConnection.Questions.Add(newQuestion);
            newConnection.SaveChanges();

            //redirect to quiz page
            return RedirectToAction("Quiz", new { id = quiz_id });
        }

        public ActionResult newAnswer(int id)
        {
            Question question = newConnection.Questions.Find(id);
            return View(question);
        }

        public ActionResult ConfirmAnswer(string answer, int value, int question_id)
        {
            Answer temp = new Answer();
            temp.answer = answer;
            temp.value = value;
            temp.question = newConnection.Questions.Find(question_id);
            newConnection.Answers.Add(temp);
            newConnection.SaveChanges();
            return RedirectToAction("newAnswer", new { id = question_id});
        }
    }
}

BuzzJean/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BuzzJean/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BuzzJean/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>BuzzJean</h1>
    <p class="lead">Welcome to the premier application for creating and taking sweet quizzes</p>
</div>

<div class="row">
    <div class="col-md-4">
        @Html.ActionLink("Make a quiz!", "Index", "Make")
    </div>
    <div class="col-md-4">
        @Html.ActionLink("Take a quiz!", "Index", "Take")
    </div>
    <div class="col-md-4">
        @Html.ActionLink("See past results!", "Index", "Receipt")
    </div>
</div>

BuzzJean/Views/Make/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>What's your quiz title?!?!?!?</h2>

<form method="POST">
    Title: <input name="title" type="text" />
    <button type="submit">Create Quiz</button>
</form>

BuzzJean/Views/Make/Index.cshtml
@model IEnumerable<BuzzJean.Models.Quiz>

@{
    ViewBag.Title = "Index";
}

<h2>List of quizzes that have been made</h2>

<ul>
    @foreach (var quiz in Model)
    {
        <li>
          <a href="/Make/quiz/@quiz.id">@quiz.title</a>
        </li>
    }
</ul>

@Html.ActionLink("Add new quiz", "Create")

BuzzJean/Views/Make/NewQuestion.cshtml
@{
    ViewBag.Title = "NewQuestion";
}

<h2>Add a new Question to this quiz</h2>

<form action="/Make/CreateQuestion" method="POST">
    Question: <input name="question" type="text" />
    <input name="quiz_id" type="hidden" value=@ViewBag.quiz_id />
    <button type="submit">Create Question</button>
</form>

BuzzJean/Views/Make/Quiz.cshtml
@model BuzzJean.Models.Quiz

@{
    ViewBag.Title = "Quiz";
}

<h2>@Model.title</h2>

<ul>
    @foreach (var question in Model.questions)
    {
        <li>
            <a href="/Make/newAnswer/@question.id">@question.question</a>
        </li>
    }
</ul>

<a href="/Make/NewQuestion/@Model.id">Add a new question</a>

BuzzJean/Views/Make/newAnswer.cshtml
@model BuzzJean.Models.Question

@{
    ViewBag.Title = "Add Answers";
}
<h2>@Model.question</h2>

<!-- Show a list of all previous answers to the given question-->
@foreach (var answer in Model.answers)
{
    <li>@answer.answer - @answer.value</li>
}

<!-- Show new answer form -->
<form action="/Make/ConfirmAnswer" method="post">
    Answer Text: <input type="text" name="answer" /> <br />
    Answer Value: <input type="number" name="value" /> <br />
    <input type="hidden" name="question_id" value="@Model.id" />
    <button type="submit">Add Answer</button>
</form>

@Html.ActionLink("Back to Questions", "Quiz", "Make", new { id = Model.quiz.id }, new {@class = "btn btn-primary"})

BuzzJean/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>